#!/usr/bin/env python3
"""
Cube Assignment Generator

Generates cube_id assignments for base and query vectors using grid partitioning
on 2D metadata. Each vector is assigned to a cube based on which grid cell
it falls into in the attribute space.

Output format:
    [n: uint64 (8 bytes)] [cube_id_0: uint32 (4 bytes)] [cube_id_1: uint32] ...
"""

import numpy as np
import struct
import argparse
from pathlib import Path


def read_fvecs(filename):
    """Read .fvecs file format to get vector count"""
    with open(filename, 'rb') as f:
        # Read first vector to get dimension
        dim = struct.unpack('i', f.read(4))[0]
        f.seek(0)

        vectors = []
        while True:
            dim_bytes = f.read(4)
            if not dim_bytes:
                break
            d = struct.unpack('i', dim_bytes)[0]
            vec = struct.unpack('f' * d, f.read(4 * d))
            vectors.append(vec)

        return len(vectors), dim


def load_metadata(metadata_path):
    """
    Load metadata from binary file

    Format: [n: size_t (8 bytes)] [d: size_t (8 bytes)] [vectors...]
    """
    with open(metadata_path, 'rb') as f:
        n = struct.unpack('Q', f.read(8))[0]
        d = struct.unpack('Q', f.read(8))[0]

        metadata = np.zeros((n, d), dtype=np.float32)
        for i in range(n):
            metadata[i] = np.frombuffer(f.read(4 * d), dtype=np.float32)

    return metadata


def compute_cube_ids(metadata, num_cubes_per_dim):
    """
    Compute cube_id for each vector using grid partitioning.

    Args:
        metadata: numpy array of shape (n, 2) with 2D attribute values
        num_cubes_per_dim: number of cubes along each dimension

    Returns:
        numpy array of cube_ids of shape (n,)
    """
    n = metadata.shape[0]

    # Assume metadata values are in [0, 100] range (as generated by generate_metadata.py)
    # Scale to [0, 1] and then to [0, num_cubes_per_dim)
    normalized = metadata / 100.0

    # Compute cell indices for each dimension
    cell_indices = np.floor(normalized * num_cubes_per_dim).astype(np.int32)

    # Clamp to valid range [0, num_cubes_per_dim - 1]
    cell_indices = np.clip(cell_indices, 0, num_cubes_per_dim - 1)

    # Compute cube_id = dim0_id * num_cubes_per_dim + dim1_id
    cube_ids = cell_indices[:, 0] * num_cubes_per_dim + cell_indices[:, 1]

    return cube_ids


def save_cube_ids(cube_ids, output_path):
    """
    Save cube_ids to binary file

    Format: [n: uint64] [cube_id_0: uint32] [cube_id_1: uint32] ...
    """
    n = len(cube_ids)

    with open(output_path, 'wb') as f:
        # Write number of vectors
        f.write(struct.pack('Q', n))
        # Write cube_ids
        for cube_id in cube_ids:
            f.write(struct.pack('I', cube_id))

    print(f"Saved {n} cube_ids to: {output_path}")


def load_cube_ids(cube_id_path):
    """
    Load cube_ids from binary file

    Format: [n: uint64] [cube_id_0: uint32] [cube_id_1: uint32] ...
    """
    with open(cube_id_path, 'rb') as f:
        n = struct.unpack('Q', f.read(8))[0]
        cube_ids = np.frombuffer(f.read(4 * n), dtype=np.uint32)

    return cube_ids


def main():
    parser = argparse.ArgumentParser(
        description='Generate cube_id assignments using grid partitioning'
    )
    parser.add_argument(
        '--base', type=str, required=True,
        help='Path to base vectors .fvecs file (used to verify count)'
    )
    parser.add_argument(
        '--query', type=str, required=True,
        help='Path to query .fvecs file (used to verify count)'
    )
    parser.add_argument(
        '--metadata', type=str, required=True,
        help='Path to metadata .bin file (2D attribute values)'
    )
    parser.add_argument(
        '--output-base', type=str, required=True,
        help='Output path for base cube_ids .bin file'
    )
    parser.add_argument(
        '--output-query', type=str, required=True,
        help='Output path for query cube_ids .bin file'
    )
    parser.add_argument(
        '--num-cubes', type=int, default=16,
        help='Number of cubes per dimension (default: 16, results in 16x16=256 cubes)'
    )

    args = parser.parse_args()

    # Load metadata
    print(f"Loading metadata from: {args.metadata}")
    metadata = load_metadata(args.metadata)
    print(f"Metadata shape: {metadata.shape}")

    # Verify metadata is 2D
    assert metadata.shape[1] == 2, f"Expected 2D metadata, got {metadata.shape[1]}D"

    # Get vector counts from fvecs files
    print(f"\nVerifying vector counts...")
    base_count, _ = read_fvecs(args.base)
    query_count, _ = read_fvecs(args.query)

    print(f"Base vectors: {base_count}")
    print(f"Query vectors: {query_count}")
    print(f"Metadata vectors: {metadata.shape[0]}")

    # Verify metadata count matches base count (we use base metadata for both)
    assert metadata.shape[0] == base_count, \
        f"Metadata count ({metadata.shape[0]}) doesn't match base count ({base_count})"

    # Compute cube statistics from base metadata
    print(f"\nComputing cube assignments with {args.num_cubes}x{args.num_cubes} grid...")

    # For base: first half of metadata is base, second half is query
    # Actually, the metadata file contains all vectors (base + query)
    # Let's split: first base_count is for base, rest is for query
    if metadata.shape[0] == base_count + query_count:
        base_metadata = metadata[:base_count]
        query_metadata = metadata[base_count:]
    elif metadata.shape[0] == base_count:
        # If metadata only has base, use same for both (for testing)
        base_metadata = metadata
        query_metadata = metadata[:query_count] if query_count <= len(metadata) else metadata
    else:
        raise ValueError(
            f"Metadata count ({metadata.shape[0]}) doesn't match "
            f"base ({base_count}) + query ({query_count})"
        )

    # Compute cube_ids
    base_cube_ids = compute_cube_ids(base_metadata, args.num_cubes)
    query_cube_ids = compute_cube_ids(query_metadata, args.num_cubes)

    # Print statistics
    print(f"\nCube assignment statistics:")
    print(f"  Base: min={base_cube_ids.min()}, max={base_cube_ids.max()}, "
          f"unique={len(np.unique(base_cube_ids))}")
    print(f"  Query: min={query_cube_ids.min()}, max={query_cube_ids.max()}, "
          f"unique={len(np.unique(query_cube_ids))}")

    # Show distribution
    base_unique, base_counts = np.unique(base_cube_ids, return_counts=True)
    print(f"  Base cube distribution: mean={base_counts.mean():.1f}, "
          f"std={base_counts.std():.1f}, min={base_counts.min()}, max={base_counts.max()}")

    # Save cube_ids
    print(f"\nSaving cube_ids...")
    save_cube_ids(base_cube_ids, args.output_base)
    save_cube_ids(query_cube_ids, args.output_query)

    print(f"\nDone!")


if __name__ == '__main__':
    main()
