#!/bin/bash
# Quick Reference - Common Commands

echo "=========================================="
echo "Filtered Vector Search - Quick Reference"
echo "=========================================="
echo ""

echo "1. GENERATE METADATA"
echo "   Uniform distribution (2D):"
echo "   $ python3 scripts/generate_metadata.py --data ./DATA/sift/sift_base.fvecs --output-dir ./DATA/sift --attr-dim 2 --distributions uniform"
echo ""
echo "   All distributions (2D):"
echo "   $ python3 scripts/generate_metadata.py --data ./DATA/sift/sift_base.fvecs --output-dir ./DATA/sift --attr-dim 2 --distributions all"
echo ""
echo "   Batch generate all:"
echo "   $ ./scripts/generate_all_metadata.sh"
echo ""

echo "2. GENERATE QUERY FILTERS (NEW)"
echo "   Single filter (1% selectivity, range):"
echo "   $ python3 scripts/generate_filters.py --metadata ./DATA/sift_metadata_uniform_2d.bin --query ./DATA/sift_query.fvecs --output ./DATA/filters/test.json --selectivity 0.01 --filter-type range"
echo ""
echo "   Single filter (5% selectivity, radius):"
echo "   $ python3 scripts/generate_filters.py --metadata ./DATA/sift_metadata_uniform_2d.bin --query ./DATA/sift_query.fvecs --output ./DATA/filters/test.json --selectivity 0.05 --filter-type radius"
echo ""
echo "   Batch generate all (32 files: 4 dists × 2 types × 4 selectivities):"
echo "   $ ./scripts/generate_all_filters.sh"
echo ""

echo "3. GENERATE GROUNDTRUTH (NEW)"
echo "   Single groundtruth (K=100):"
echo "   $ python3 scripts/generate_groundtruth.py --base ./DATA/sift_base.fvecs --query ./DATA/sift_query.fvecs --metadata ./DATA/sift_metadata_uniform_2d.bin --filters ./DATA/filters/test.json --output ./DATA/groundtruth/test_gt.ivecs --k 100"
echo ""
echo "   Batch generate all (32 files):"
echo "   $ ./scripts/generate_all_groundtruth.sh"
echo ""

echo "4. VISUALIZE METADATA"
echo "   Single distribution:"
echo "   $ python3 scripts/visualize_metadata.py --metadata ./DATA/sift/sift_metadata_uniform_2d.bin --output-dir ./visualizations/sift"
echo ""
echo "   Compare distributions:"
echo "   $ python3 scripts/visualize_metadata.py --metadata ./DATA/sift/sift_metadata_*_2d.bin --output-dir ./visualizations/sift --compare"
echo ""
echo "   Batch visualize all:"
echo "   $ ./scripts/visualize_all_metadata.sh"
echo ""

echo "5. BUILD FILTERED INDEX (C++)"
echo "   Grid index:"
echo "   $ ./build/src/test_grid_index ./DATA/sift/sift_base.fvecs ./DATA/sift/sift_metadata_uniform_2d.bin ./DATA/sift/index.grid 2"
echo ""
echo "   R-tree index:"
echo "   $ ./build/src/test_rtree_index ./DATA/sift/sift_base.fvecs ./DATA/sift/sift_metadata_uniform_2d.bin ./DATA/sift/index.rtree 2"
echo ""

echo "6. VISUALIZE RESULTS"
echo "   Filter selectivity:"
echo "   $ python3 scripts/visualize_results.py --metadata ./DATA/sift/sift_metadata_uniform_2d.bin --output-dir ./visualizations/results"
echo ""
echo "   With performance metrics:"
echo "   $ python3 scripts/visualize_results.py --metadata ./DATA/sift/sift_metadata_uniform_2d.bin --results ./results/perf.json --output-dir ./visualizations/results"
echo ""

echo "=========================================="
echo "COMPLETE WORKFLOW:"
echo "  1. ./scripts/generate_all_metadata.sh      # Generate metadata"
echo "  2. ./scripts/generate_all_filters.sh       # Generate filters"
echo "  3. ./scripts/generate_all_groundtruth.sh   # Generate groundtruth"
echo "  4. ./scripts/visualize_all_metadata.sh     # Visualize"
echo "=========================================="
echo ""

echo "SELECTIVITY LEVELS:"
echo "  1%  = ~10,000 points (out of 1M)"
echo "  5%  = ~50,000 points"
echo "  10% = ~100,000 points"
echo "  30% = ~300,000 points"
echo ""

echo "=========================================="
echo "File Locations:"
echo "  Scripts:        ./scripts/"
echo "  Data:           ./DATA/"
echo "  Filters:        ./DATA/filters/        (NEW)"
echo "  Groundtruth:    ./DATA/groundtruth/    (NEW)"
echo "  Visualizations: ./visualizations/"
echo "  Documentation:  ./scripts/README.md"
echo "                  ./scripts/FILTERS_README.md  (NEW)"
echo "=========================================="

